language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "boilermaker-demo-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: staging-alesp-dados-abertos # see README
  api_key:
    secure: "L8yq+d/g3PkwMlV0BpF11Tw4dhDZD+jW7D3RI0X1JJWEqrrnbyl32eg9dd9d/bJp6vLifqsGN/QB91bJ4cNeIW+4QyETKZ37CT/w05L907F9H8Wdkr/OIstoMJTMsRH0+iXT3c99JT0AWJUKrTrCLSHIJ4PRAa+u+BeOOS5iaYjtsnf3i9Bpcs1o9xw3EKK9JuN9r8xw/tVuXT6UKYwYyujkLhDENF8oEOPAmdStjXBaNQWJPprH1kbkqE49XS/AxPeudW3bWLGeTiGgATe1hQhvM5+KwmeNWE6VElMOGUSYzgHdO/raOyLCdekFOQQ4B5zENg3Cyhm1fH5cPfwuUidvhM+0+y0afRjppm1nBdms3zAveOKm4vkp5ACc3eHmAj/N0zN7Wpkbhu95lIZybnZm3kOeNt4vITXJ7dzr3ihK3KF+pSWfR2ZRYO4r0vF3LayH5+yYBQstUhieOpVzLkvfchWd7U12DA972/v+QYUkN4OR2kACWCOwa+EaWhXT1JKEjUCmuXBknGDokNEdVRnrrjw5+Lu6u4WLELq89EXbb9NX4FX6EWWJIas8wRBxWzTfnA+D7oMkclWJd/7U3epdhiVrUrkWiv6ux52C/da6iDfC9ZP9tMXwxo777DUpC3q2G2CSiWbvDhXzcS1mA0v+5H2F7C669cvOqs3JoL4=" # see README
